### ISSUE TITLE
support for rtmp streams

### ISSUE THREAD

**Issue by muhammedabuali** [clementine-player/Clementine#4787] opened 2015-03-28 01:31 UTC
it would be great to add support for rtmp streams to clementine.

**Comment by Tatsh** [comment] 2015-03-28 04:08
Who is still doing RTMP streams? Most things have moved from RTMP to RTMPE because they want DRM on the stream.

Not everything about RTMPE is known yet. https://en.wikipedia.org/wiki/Protected_Streaming

**Comment by muhammedabuali** [comment] 2015-03-28 04:14
to answer your question, an old website of a popular regional station. [link to website](http://www.ertu.org/quran/QuranKareem.html).

I do not know much about other streaming services though

**Comment by Tatsh** [comment] 2015-03-28 04:18
This is a duplicate by the way. #3927 which you commented on.

As for that site, and really any RTMP stream, I would recommend you try rtmpdump. I have used it a lot.

**Comment by muhammedabuali** [comment] 2015-03-28 10:01
yes, I found out about it yesterday and got it to work with the help of wireshark. but I thought having it in clementine. along with other streaming services is neat.

**Comment by ArnaudBienner** [comment] 2015-03-28 15:32
Duplicate of #3927

**Closed by ArnaudBienner** 2015-03-28 15:32 UTC
