### ISSUE TITLE
Spotify Not Signing In

### ISSUE THREAD

**Issue by darkMatterSound** [clementine-player/Clementine#4873] opened 2015-05-26 22:30 UTC
When I try to connect to Spotify, it just sits there in an infinite "Signing In..." stage.  I have a Spotify premium account and the Spotify plugin is installed.  The only way I can get it to stop is by closing Clem and reopening.

Linux Mint 17.1 w/kernel - 3.18.2-031802-generic
Clementine Version 1.2.3-1162-gfd645b3

**Comment by Kwaadpepper** [comment] 2015-07-23 18:00
I also have this problem in lastest clementine build 
Kubuntu 15.04 kernel 4.0.0-4-generic
Version 1.2.3-1259-ga568250

**Comment by Chocobozzz** [comment] 2015-07-23 18:14
Duplicate of https://github.com/clementine-player/Clementine/issues/3930

**Closed by Chocobozzz** 2015-07-23 18:14 UTC

**Comment by hiwigiwi** [comment] 2021-02-26 10:42
@SVMBrown what *exactly* did you install? I am also on Manjaro with the same problem...

**Comment by SVMBrown** [comment] 2021-02-26 16:55
@hiwigiwi I haven't looked at this in a while, but a search of my installed packages brought up:

qt4 4.8.7-29.1

in the community repository.
Was installed on the date that I posted my comment, so it is most likely the package that fixes it.

Hope that helps!

**Comment by kyberorg** [comment] 2021-03-03 15:09
@hiwigiwi  qt4 comes from [AUR](https://aur.archlinux.org/packages/qt4/)
