### ISSUE TITLE
Playing any track currently results in 'buzzing'

### ISSUE THREAD

**Issue by flocculant** [clementine-player/Clementine#5221] opened 2016-01-22 19:24 UTC
Hard to describe the sound I'm getting playing music currently.

I have tried various filetypes from mp3 to flac.

I am using Xubuntu 16.04 (obviously dev version) with both the standard repo version of Clementine and the version available via the clementine-dev ppa.

Any other player I try works fine. (Audibly at least)

Screencast of what I'm getting at https://sendvid.com/sa7b0i4n

**Comment by narunlifescience** [comment] 2016-01-22 19:27
is equalizer enabled ?

**Comment by flocculant** [comment] 2016-01-22 19:33
No.

I've tried a clean install of xubuntu, followed by updates/upgrades xubuntu needed,then a clean install of clementine,.

Still the same.

So - install the 16.04, update it - install Clementine (either repo or ppa)

Hit this.

I did try looking back to see what else had upgraded when I first caught this (week or so ago) but given I run dev xubuntu, I was seeing gcc/python/qt/gstreamer all hitting about the same time.

**Comment by elnull** [comment] 2016-01-23 15:28
I've got same issue on Ubuntu 16.04 and Celementine 1.3.0rc1 from ppa.

**Comment by flocculant** [comment] 2016-01-23 15:34
Thanks - sort of :)

At least I now know it's not just a local issue. There is a launchpad bug - https://bugs.launchpad.net/ubuntu/+source/clementine/+bug/1537184/+affectsmetoo Though not sure if that was just superfluous.

**Comment by nazar-pc** [comment] 2016-01-23 18:08
The same here on Ubuntu 16.04 x64.
ALSA output works fine, problems only with PulseAudio output. But ALSA outputs cuts first 0.5-1s of playback, which is quite annoying.

This behavior happens for approximately 2 weeks now, thought something temporary, but looks like permanent.

**Comment by Ferroin** [comment] 2016-01-25 12:40
Just as another datampoint, I've been unable to reproduce this on a Gentoo box with the same version of PulseAudio as used in Ubuntu 16.04 (including copying all the build flags, and matching the compiler version used), so I'd say it's likely to be something Ubuntu specific, or PulseAudio itself is not directly responsible (possibly something it links to is).

**Comment by flocculant** [comment] 2016-01-25 12:45
From the changelog seems nothing changed with PA since December - on the other hand there were a slew of gstreamer  changes happened (if memory serves correctly) at about the same time playback on Clementine went south.

gst-plugins-bad1.0 specifically http://changelogs.ubuntu.com/changelogs/pool/universe/g/gst-plugins-bad1.0/gst-plugins-bad1.0_1.7.1-1ubuntu1/changelog

Not found any other media/music player giving the same issue though

**Comment by flocculant** [comment] 2016-01-25 18:18
mmm - not able to test it with alsa, it won't keep alsa as the output

**Comment by nazar-pc** [comment] 2016-01-25 18:47
It always say AUTO (which is a bug, it actually correctly applies settings, so just select ALSA, save and start playing song again).

**Comment by flocculant** [comment] 2016-01-26 16:37
Then perhaps I'm seeing another issue.

If I set to alsa - apply, then play a track - all is good. If I then OK so the pref page closes then I end up with pa again and the buzzing.

For the record, I've purged and removed any local ~/home configs/caches and started Clementine up vanilla - both repo version and the dev ppa version.

**Comment by flocculant** [comment] 2016-01-29 20:01
Forget that last comment - seems to be ok after a complete purge.

**Comment by nazar-pc** [comment] 2016-01-29 20:07
Package and dependencies purging doesn't help and I do not want to loose as settings when purging user settings.

**Comment by dkessel** [comment] 2016-02-13 17:35
I have the same here on Xubuntu 16.04 x64

**Comment by flocculant** [comment] 2016-02-15 16:26
appears to be https://bugzilla.gnome.org/show_bug.cgi?id=762085

**Comment by nazar-pc** [comment] 2016-02-16 01:33
I can confirm, downgraded `gstreamer1.0-plugins-base` to `1.6.3-1ubuntu1` from Wily and Clementine now plays fine.

**Comment by elnull** [comment] 2016-02-16 14:23
On my Ubuntu 16.04,  gstreamer1.0 version 1.7.1
gst-launch-1.0 filesrc location=01.mp3 ! mad ! audioconvert ! audioresample  ! pulsesink
plays fine.

**Comment by flocculant** [comment] 2016-02-23 07:52
got new gstreamer base package today - reset clementine to use pulse - all working properly again here

**Comment by nazar-pc** [comment] 2016-02-23 08:31
Confirm, with gstreamer 1.7.2 everything works fine again.

**Comment by elnull** [comment] 2016-02-23 09:46
After gstreamer update to 1.7.2 clementine plays fine.

**Comment by nazar-pc** [comment] 2016-02-23 12:27
@flocculant, maybe we can close this issue now?

**Closed** 2016-02-23 12:39 UTC
