### ISSUE TITLE
Moodbar not working on development builds

### ISSUE THREAD

**Issue by Dominiquini** [clementine-player/Clementine#4575] opened 2014-10-09 22:59 UTC
In the last development builds the moodbar is not working. Here is one screenshot:
http://imgur.com/EKR8AC0
I'm using version 1.2.3-787-gaa3671b.
But the problem also happens in previous versions...
Seeking with mouse wheel also broken (#4568)
I'm testing in Ubuntu 12.04 and using development ppa (ppa:me-davidsansome/clementine-dev), but the builds on http://builds.clementine-player.org/ubuntu-precise/ also have these problems.
The stable build "1.2.3" are OK!!!

Thank you.

**Comment by Dominiquini** [comment] 2015-01-05 01:10
In version 1.2.3-954-g2cc560f this problem still persists.
Is there any information you can send to help to identify this bug?

Thank you.

**Comment by KottV** [comment] 2015-01-17 06:20
Confirm. Seek/moodbar broken.

**Comment by TheUbuntuGuy** [comment] 2015-07-12 16:48
Is this still an issue in the current dev builds? I feel like this was fixed in one of the many moodbar changes that happened since then.

**Comment by ArnaudBienner** [comment] 2016-02-18 15:05
Duplicate of #4770

**Closed by ArnaudBienner** 2016-02-18 15:05 UTC
