### ISSUE TITLE
Enabling an equalizer crashes clementine

### ISSUE THREAD

**Issue by 842Mono** [clementine-player/Clementine#5368] opened 2016-05-07 12:01 UTC
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 14.04 64bit
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Issue appeared after the latest update.
I just enable a custom equalizer I have from before (while a track is running) and Clementine crashes.

### Steps to reproduce the problem (only for bugs)
Tools>Equalizer>check Enable Equalizer *kaboom* it crashes XD

**Comment by ArnaudBienner** [comment] 2016-05-08 16:52
Duplicate of #4541

**Closed by ArnaudBienner** 2016-05-08 16:52 UTC
