### ISSUE TITLE
ratings get lost

### ISSUE THREAD

**Issue by naraesk** [clementine-player/Clementine#5429] opened 2016-07-02 09:24 UTC
### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version:  1.3.1

### Expected behaviour / actual behaviour

I have a huge music collection (about 20.000 songs) and every song is rated. However, from time to time clementine uses some ratings. I can't see a pattern and it just occurs to some files, but it happens again and again.

I can definetly say, that it is not related to playing the song or updating metadata. In some cases the song was rated a year ago and wasn't even played once since then. And suddenly ... no rating anymore.

**Comment by sabret00the** [comment] 2016-07-02 11:48
It's related to #3064

**Comment by naraesk** [comment] 2016-07-03 16:31
Thanks, it's probably the same issue.

**Comment by ArnaudBienner** [comment] 2016-07-08 15:20
Closing as duplicate of #3064

**Closed by ArnaudBienner** 2016-07-08 15:20 UTC
