### ISSUE TITLE
16k is inverted in equalizer

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#695] opened 2013-12-06 13:25 UTC
_From [himynameiszacHandiamapirate](https://code.google.com/u/116275170679458301339/) on September 05, 2010 04:50:54_

Never thought I'd see the day. Maybe it's just my setup (though I tested on speakers and headphones), but give this a shot: Go into the equalizer while anything is playing, and adjust the 16k slider up and down. On my system, sound is actually clearer with the slider all the way down... much clearer. Pumping up the 16k seems to actually be creating some interference or something, for me. So, assuming this is happening on other machines, either the equalizer we're using is incorrectly adjusting this band, or it really is just way too high for us to be messing with.

Thoughts continue below, on the assumption this needs to be changed, and isn't just happening for me.

I'm not really sure what's to be done here... a nine-band equalizer would be kinda odd, and I definitely use the other bands (if only to adjust the low end so my subwoofer doesn't eat me... damned lack of a subwoofer volume control). Thoughts? /am I crazy and only experiencing this on my end?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=695_

**Comment by ArnaudBienner** [comment] 2015-03-14 00:05
Now we migrated to Gstreamer 1.0, can someone try again to see if the problem is gone?

**Comment by dancemasterglenn** [comment] 2015-03-14 02:50
I got the same result from the most recent compiled windows build... but maybe I had some leftover config files from my previous install? This doesn't seem like the kind of issue that would carry over in that way, though. :(

Can anyone else test and confirm?

**Comment by KitsuneRale** [comment] 2015-07-24 02:54
I'm still having this on my Windows machine, with recent nightly builds.

**Comment by santigl** [comment] 2016-02-14 07:56
The bug is still there with GStreamer 1.0 in Debian 64 bits.

However, I have been playing with the values, and noticed that the behavior could also be replicated with the first band. 

It turns out that for the first and last bands GStreamer uses shelve filters, calling different routines than for the rest of the frequencies.

So, what I did as a workaround (assuming that there is a bug in GStreamer's implementation of those corner cases), is to generate two dummy bands at each end of the spectrum. They are dummies because their bandwidth is set to 0, and they are centered at 20Hz and 20000Hz.

While doing that, I also tried moving the bands to follow the [ISO 266](http://www.zytrax.com/tech/audio/equalization.html#iso-frequencies) standard. 

According to that standard, the center frequencies are doubled at each step: 30, 60, 130, 250, 500, 1000, 1200, 4000, 8000, 16000 [Hz]. (Actually, those are the human-friendly labels, the actual frequencies are, approximately, 31.62, 63.10, 125.89, 251.19, 501.19, 1000.0, 1195.3, 3981.1, 7943.3, and 15848.3 [Hz].)

The bandwidth of each band of the equalizer is variable, and it is calculated by a simple formula.

It'd be great if you wanted to test it out to verify it works in other platforms. I've committed the changes to my fork. Just let me know...

**Comment by Ferroin** [comment] 2016-02-15 16:04
I've cloned your fork on my laptop and built and tested that things work for Linux (For reference, it's a 64-bit x86 system running bleeding-edge Gentoo).  If somebody can provide a build for Windows I can test that too (I have access to Windows systems to test on, I just don't have the time, patience, or tools required to build any software for said systems).  Somebody else is going to have to test on OS X though, as I have no Apple hardware or software.

**Comment by santigl** [comment] 2016-02-15 19:50
Great, thanks for testing it. I am also in that situation with regards to Windows and Mac.

**Comment by ArnaudBienner** [comment] 2016-02-15 21:19
@santigl I will merge the changes you did on a separate branch on the main repo, and push it. Then I will trigger a build on buildbot so anyone can access build for every platform.

**Comment by santigl** [comment] 2016-02-15 21:22
Ok. Do you want me to remove the debug messages first so that if it works it can be merged with master directly, or we can clean it later?

**Comment by ArnaudBienner** [comment] 2016-02-15 21:23
I've forced a build for Windows. Should be in http://builds.clementine-player.org/win32/release/ once done (git SHA is 34cbddf837dc)
You can check the status here.
http://buildbot.clementine-player.org/grid
However, Mac build seems to be broken atm :( Maybe @hatstand or @davidsansome can have a look, since I'm not sure what is wrong.

**Comment by ArnaudBienner** [comment] 2016-02-15 21:24
@santigl yes: I've done this only to allow testing: we will clean later if needed

**Comment by santigl** [comment] 2016-02-15 21:33
Perfect. I installed the build in Windows 7 64 bits and it is working as expected.

**Comment by Ferroin** [comment] 2016-02-16 12:18
I can confirm that the Windows build is working correctly on 64-bit Windows 8.1 as well.

**Comment by hatstand** [comment] 2016-02-16 18:21
Mac build is fixed and running here: https://buildbot.clementine-player.org/builders/Mac%20Release/builds/61

**Comment by hatstand** [comment] 2016-02-16 18:27
https://builds.clementine-player.org/mac/clementine-1.2.3-1568-g34cbddf.dmg

**Comment by Ferroin** [comment] 2016-03-02 13:48
OK, one of my friends who has a Mac (and for some reason refuses to get a GitHub account) finally had some spare time to test this, and it appears to be working correctly on OS X 10.11.3 as well.

**Comment by santigl** [comment] 2016-03-02 15:47
Great, so all platforms are covered. Thanks, Ferroin!

I'll make a pull request.

**Comment by Ferroin** [comment] 2016-03-04 16:03
It was pointed out by @TheUbuntuGuy in a comment on the pull request that the switch to ISO 266 frequencies will change how each equalizer preset sounds.  I'm not certain though whether we should change them, as I've seen other software using identical curves with ISO 266 bands (VLC uses the ISO bands, and I think iTunes, WMP, Banshee and Exaile do also, and they have essentially identical equalizer curves to what we use for equivalent presets), so I think that the versions of said curves used in Clementine may have been used incorrectly originally.

**Comment by dancemasterglenn** [comment] 2016-03-05 19:48
Never been a big fan of the 266 bands. :( I was actually a proponent of the change to the standard we were using, as it's the same type of bands used in Winamp and Audacious. I've always preferred the tweakability of the sound from these bands as compared to ISO 266 EQ players, but as you can see from this old issue we ran into quite an issue with (apparently!) more than one band.

My vote would be to keep the bands the way they were, but to find some sort of fix that will un-invert the two problematic bands, but since the issue was never resolved I assume that's easier said than done. If it is possible to fix what we've got though, does anyone feel so strongly in favor of ISO 266 that they would argue to use it instead as a rather blunt solution to this issue?

**Comment by santigl** [comment] 2016-03-05 21:19
As of the presets, I agree with @Ferroin: I had compared the current presets' curves with the ones implemented in VLC, and they are very similar (although their absolute values are different, because VLC uses a different dB range).

Then the only issue would be user-generated presets, but I thought it would be safe to assume that they would still have to be corrected for the fixed band.

The reason why I propose to change to ISO 266 bands is to offer a more predictable behavior and a more consistent experience. Bear in mind that the standard not only sets the frequency spacing, but also the bandwidth of each one. The latter is implicit in most cases, and the only workaround would be to offer the specifications in detail. But even in that case, I imagine that different people may have different wishes as to how those values are defined. 

This is a matter that can end up being highly subjective, depending on taste, equipment and environment. I figured that adopting the standard might help fix one part of those variables and offer a reliable tool.

**Comment by Ferroin** [comment] 2016-03-07 13:56
@dancemasterglenn The solution is orthogonal to any changes in the frequencies and bandwidths.  The pull request has both as one commit, although there is no reason I can see from looking at the diffs myself why they couldn't be separated into two changes.

As far as the usage of ISO 266 instead of current bands, why don't we just add a option to select one or the other?  This would take more work, but on the other hand having both options would be a potential selling point compared to other music players (most that I've seen have no option to change the bands at all).  Personally, I'd rather use the ISO 266 bands myself, but that's mostly because almost all the audio software I work with personally uses the ISO bands, and I like consistency.  I can entirely understand however why some people may want to use the current bands.

**Comment by narunlifescience** [comment] 2016-03-07 14:18
IMHO adding an option to switch between ISO 266 & current is not that good.. if variable frequency boost/damp is required, then only a parametric EQ is the right candidate..

**Comment by Ferroin** [comment] 2016-03-07 14:46
The intent was not full variable frequency equalization, but to allow people the choice to use our current bands (which are apparently consistent with Audacious and Winamp, and probably some other software out there), or the ISO 266 bands (which are consistent with at least VLC, and I believe also WMB, iTunes, Banshee, and Exaile, as well as most audio equipment I've seen, and are what the EQ curves we are using were based on in the first place).  I would love to have a full parametric equalizer in Clementine (I know a number of people who would switch from what they're currently using _just_ for that functionality), but as of right now, it's not something that is likely to happen, and until it does, having some choice is better than none.

**Comment by narunlifescience** [comment] 2016-03-07 14:55
don't you think any one using ISO 266 could tweak their bands to match previous band settings ? even though there are changes to base frequencies, they should be able to tweak appropriately to sound the similar to previous settings approx...

**Comment by TheUbuntuGuy** [comment] 2016-03-07 14:57
I do not like the idea of keeping both sets of bands. @ArnaudBienner will probably back me up on this one. This IMO falls into the category of unnecessary and ultimately confusing options for the majority of users. Parametric equalization is the "proper solution", but I can't say whether that will happen any time soon.

If we are concerned about users getting mad at the sudden band changes to ISO 266, we could offer a "conversion" (interpolation) upon startup after the upgrade, similar to what we do when a change in the SQLite requires a rescan of the Library.

**Comment by narunlifescience** [comment] 2016-03-07 15:06
@TheUbuntuGuy is there a need to provide conversion? it is just 10 bands to tweak.. lol

**Comment by TheUbuntuGuy** [comment] 2016-03-07 15:09
No, but I know not everyone will read the changelog. I can just see some people complaining that everything 'sounds weird now'. People can do it manually of course, but it might be worth at least pointing out that the bands changed.

**Comment by narunlifescience** [comment] 2016-03-07 15:10
well.. fair enough..

**Comment by Ferroin** [comment] 2016-03-07 15:13
Personally, I don't really care whether or not there's an option for it, I was just trying to offer a potential stop-gap solution until we could get something like parametric equalization.  I do think we should move to the ISO bands, as that provides consistency with a larger majority of audio software.  I also think that it may be difficult to properly interpolate the curves,as we ideally want to go for the same perceived sound, which may not match what you would get from simple interpolation.  Ideally though, we should just provide presets to match the current curves, and presets to match what other music players with the ISO 266 bands use.

**Comment by JulianVolodia** [comment] 2016-03-07 21:42
@Ferroin , could I help in any way? Should the PR would be devided into 2 commits? Should it be reviewed by somebody? What is bad with it? Maybe just merge part, close that and extract "a meat" part of next conclusions to new issue?

We have about 1,5 k issues to do - maybe just get things done? :)

Best regards!

**Comment by Ferroin** [comment] 2016-03-08 12:27
At a minimum, the fix for this particular issue with the equalizer bands needs to get merged.  Splitting the PR to two separate ones and moving the discussion regarding switching to ISO 266 bands would probably be best, but that should really be up to someone else, as I'm not directly involved in development for Clementine.

@santigl Any chance you could either update the PR or post a new one with just the fix for this issue, then we could open a new issue regarding the choice of EQ bands?

**Comment by santigl** [comment] 2016-03-08 18:16
Sure, @Ferroin. I was going to propose that, since the two modifications are independent. (I should have done two separate commits, but at the time it made sense to combine them into an overhaul of the equalizer).

I'll submit only the fix as a pull request so we can close this issue and then keep discussing the adoption of the standard.

**Closed** 2016-03-29 14:35 UTC
Labels: bug, imported, Priority-Medium
