### ISSUE TITLE
[Feature Request] Dynamic Playlists: Combine AND and OR

### ISSUE THREAD

**Issue by desputinski** [clementine-player/Clementine#5504] opened 2016-10-02 07:14 UTC
Hi, I have a feature-Request:
Being able to Combine AND and ORs in dynamic playlist / intelligent Playlists.

For example:
- I want to create a playlist that contains all songs containing the word "Pop" and "Rock" in the genre field.
- All all songs should have a rating above 3 stars

At the moment Clementine cannot do that.  If I choose _"Genre must contain Pop" OR "Genre must contain Rock" OR "More than 3 stars rating"_ I also get songs from different genres.
The solution would be to combine the AND and ORs like this:

_"Genre must contain Pop" OR "Genre must contain Rock"
**AND** "More than 3 stars rating"_

best regards
desputin

**Comment by gordon-morehouse** [comment] 2017-05-23 23:29
Duplicate of #4744.

**Closed** 2017-05-24 08:13 UTC
