### ISSUE TITLE
Clementine steals keyboard focus

### ISSUE THREAD

**Issue by pwd-github** [clementine-player/Clementine#6204] opened 2018-11-17 13:57 UTC
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora 29
- Clementine version: 1.3.1 (Qt5)

### Expected behaviour / actual behaviour
When Clementine launches, the keyboard becomes unresponsive, unable to register any input anywhere on the system.

### Steps to reproduce the problem (only for bugs)
1. Launch Clementine
2. Attempt to type

**Comment by szpak** [comment] 2018-11-17 15:44
There is a workaround with mentioned in the Fedora [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1643937) to remove all the custom global shortcuts. However, people might still want to use them.

**Comment by szpak** [comment] 2018-11-17 15:45
@pwd-github Do you use Wayland (#5462) or you have also a problem with X11?

**Comment by szpak** [comment] 2018-11-17 15:46
Anyway it's probably a duplicate of #6191 (also with Xorg).

**Comment by pwd-github** [comment] 2018-11-17 15:47
I'm on xWayland I believe, so probably is a dupe of #6191

**Comment by jonaski** [comment] 2018-11-26 20:58
Can someone clarify this. Is this a wayland problem or not? Is it Gnome only, or all desktop environments using wayland?
Do you have "Use Gnome's shortcuts" in the settings? Did you try to turn it on?
If its only wayland, we could use QGuiApplication::platformName() to create a workaround.

**Comment by pwd-github** [comment] 2018-11-26 21:29
I have both Ubuntu and Fedora installed. It's only a Fedora problem AFAICT.

I have no idea about whether or not the issue is a problem for other desktop environments.

I cannot find a "use Gnome's shortcuts" in the settings of Clementine.

Just confirmed I'm using x11

Hopefully this all helps.

**Comment by jonaski** [comment] 2018-11-26 21:32
To see if you are using wayland: echo $WAYLAND_DISPLAY
Fedora 29 switched to wayland by default.

**Comment by pwd-github** [comment] 2018-11-26 21:34
Here's the latest from my terminal:
```[me@y70-fedora ~]$ echo $XDG_SESSION_TYPE
x11
[me@y70-fedora ~]$ echo $WAYLAND_DISPLAY

[me@y70-fedora ~]$ 
```

**Closed** 2019-01-09 04:11 UTC

**Comment by netzgestaltung** [comment] 2019-02-02 09:43
Hi guys - i am also facing this problem. 

i can see that there already is a fix but fedora does not provide an update yet 
what can i do to use clementine again for now?
