### ISSUE TITLE
Application will not allow addition of .aiff files to a playlist.

### ISSUE THREAD

**Issue by clementine-user** [clementine-player/Clementine#5419] opened 2016-06-23 00:52 UTC
[x] I checked the issue tracker for similar issues
[x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
[ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

OS: OS X versions 10.9.5, 10.10.5, and 10.11.5
Clementine Player version: 1.3.1

Application will not allow drag-and-drop of .aiff files onto a playlist.

Application will not add .aiff files from 'Playlist > Add file...' menu even when 'Files of type: All Files(*)' is selected.

Tested on multiple devices and OS versions referenced above.

Issue is reproducible:

Open Clementine and load playlist that already contains .aiff files.

Drag .aiff files from Finder window onto playlist window.

File does not add to playlist.

Selecting 'Playlist > Add file...' menu does not allow file to be added to playlist even when 'Files of type: All Files(*)' is selected.

.aiff files already in playlist playback in Clementine without issue.

This behavior does not occur in version 1.2.2 on Mac OS X above referenced OS versions.

There is no release version of 1.2.3 for Mac OS X.

**Comment by gordon-morehouse** [comment] 2017-05-24 00:06
Possible duplicate of #4921.

**Closed** 2017-05-24 08:18 UTC
