### ISSUE TITLE
Spotify search returning no results (Clementine 1.2.3 on Fedora 23)

### ISSUE THREAD

**Issue by matthewtraughber** [clementine-player/Clementine#5248] opened 2016-02-11 14:27 UTC
Issue seems to be the same as #5238 - searching for content in Spotify doesn't return any results. Playlists are available however, and do play their content.

**Comment by Chocobozzz** [comment] 2016-02-11 19:49
Duplicate of https://github.com/clementine-player/Clementine/issues/5238

**Closed by Chocobozzz** 2016-02-11 19:49 UTC
