### ISSUE TITLE
Playback fails after completing a track

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3652] opened 2013-12-13 04:37 UTC
_From [alje...@gmail.com](https://code.google.com/u/103779647280939013224/) on May 02, 2013 00:06:40_

What steps will reproduce the problem? 1. Load any playlist
2. Play a track
3. After track is finished, Clementine doesn't play the next one. Time bar stays on last second of played track. What is the expected output? What do you see instead? Expected: Clementine plays next track after finished one.
Actual: Clementine fails to play next track. What version of the product are you using? On what operating system? Clementine 1.0.1
Linux Mint 14 KDE 64-bit Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3652_

**Comment by TheUbuntuGuy** [comment] 2015-07-12 16:31
This is probably a duplicate of #4748 and #4189

**Closed** 2015-07-12 17:47 UTC
Labels: bug, imported, Priority-Medium
