### ISSUE TITLE
Soundcloud.com integration

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2540] opened 2013-12-10 13:02 UTC
_From [n...@leverton.org](https://code.google.com/u/114311011906226196511/) on December 31, 2011 20:48:26_

It would be really great to add integration with soundcloud.com as a music source.  Play/download from there, rss feed, follow, rate, add timed comments etc :)

Also mixcrate, mixcloud, etc etc

Thanks for considering this suggestion !

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2540_

**Comment by chtfn** [comment] 2015-01-19 05:27
I know this issue has the _issue_ of being too wide, but I thought I'd ask if there are any plan to get Soundcloud login into Clementine? Accessing to your "stream", playlists and own tracks would be very neat.

Anyway, the question really is: shouldn't we create new separate and precise issues, like:
- Implement login and basic user features for Soundcloud
- Improve Soundcloud search for more relevant results

... and close this issue, as a basic Soundcloud implementation is already done?

Cheers

**Comment by Chocobozzz** [comment] 2015-01-19 08:21
In the latest build there is such things for SoundCloud http://builds.clementine-player.org/ (can be unstable).

So this issue should be closed.

**Comment by chtfn** [comment] 2015-01-19 08:41
I can confirm that, I just installed clementine_1.2.3-964-gc96502e~trusty_amd64 and it works perfectly: I can link Clementine to my Soundcloud account, and then access the last few tracks in my stream, my playlists, and my own tracks.
Thank you Chocobozzz! I definitely think we can close this, and open an issue specific to the search improvements, if still needed.

**Closed** 2015-01-19 09:57 UTC
Labels: Component-Radio, enhancement, imported, Priority-Medium

**Comment by Enzoupi** [comment] 2016-01-27 19:21
I know that this issue has been closed a while ago, and I am therefore sorry to bring it up again. Since this has been implemented already, why hasn't it be integrated in the stable version already ?

**Comment by Ferroin** [comment] 2016-01-27 19:53
Two things:
1. Check Issue #5140 for a probable partial explanation of why.
2. In software in general and free software especially, 'stable' is a highly subjective term.  The nightly builds of Clementine are almost always sufficiently bug free that they are generally usable for most people, and there are a number of people (myself included) who run a local build built direct from the top of the git repository.

**Comment by fuzunspm** [comment] 2016-10-19 07:12
soundcloud login on clementine opens infinite number of winebrowser and make system halt so i can't login
