### ISSUE TITLE
nightly windows version ClementineSetup-1.2.3-1304-g509b4cc.exe missing dll

### ISSUE THREAD

**Issue by Cosmoufle** [clementine-player/Clementine#5044] opened 2015-09-18 14:53 UTC
Installed last nightly version, it says that libsqulite3-0.dll is missing on the computer

Thanks

**Comment by Chocobozzz** [comment] 2015-09-18 15:11
Duplicate of https://github.com/clementine-player/Clementine/issues/5011

**Closed by Chocobozzz** 2015-09-18 15:11 UTC
