### ISSUE TITLE
Equalizer Clementine 1.3.1-243-g420601f

### ISSUE THREAD

**Issue by JohnMGD** [clementine-player/Clementine#5554] opened 2016-12-11 18:36 UTC
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ X] I checked the issue tracker for similar issues
- [ X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: MacOS X 10.12.1
- Clementine version: 1.3.1-243-g420601f

### Steps to reproduce the problem (only for bugs) I tried to put my Equalizer settings into Clementine, but when I restart Clementine the settings are all back to zero (0), although I have saved them, also all other pre-set settings are gone.
![screen shot 2016-12-11 at 19 35 23](https://cloud.githubusercontent.com/assets/22565337/21082283/07a75ee4-bfd9-11e6-9b1d-f71605bee947.jpg)

**Comment by hatstand** [comment] 2016-12-13 16:50
Duplicate of #5539

**Closed by hatstand** 2016-12-13 16:50 UTC

**Comment by JohnMGD** [comment] 2016-12-14 17:12
I read a lot about Equaliser settings lately, and I think I am not going to use the Equalizer in Clementine anymore. Equalizers are just distorting music quality, with the use of a good quality Stereo set there is no equalizer needed. So enjoy the pure sound of how the music was meant to enjoy !!!

**Comment by JohnMGD** [comment] 2016-12-17 13:42
Found the answer. Removed the Preferences file in the Home Library folder (org.clementine-player.clementine.plist). The original Equalizer list is placed back in the Library. The Library will be emptied though, so before doing this check the Library for contents and save it !!

**Comment by JohnMGD** [comment] 2016-12-19 17:27
My conclusion was to preliminary, after restarting the computer the default Equalizer settings are all back to ZERO again, so the problem still exists !

**Comment by JohnMGD** [comment] 2017-01-03 19:16
I just downloaded version "clementine-1.3.1-269-g00c96f7", the latest version, but problems are still with the Equalizer as described above !! :(
