### ISSUE TITLE
Moodbar doesnt show seek slider beyond 35:32

### ISSUE THREAD

**Issue by kancaras** [clementine-player/Clementine#5343] opened 2016-04-19 12:27 UTC
- Operating System: Windows 7 64bit
- Clementine version: 1.3

### Expected behaviour / actual behaviour
Seek slider should be visible for all songs of all lengths at all times. Now slider disappears from 35minute 33second mark and stays hidden till the end of the song.

### Steps to reproduce the problem (only for bugs)
Play any song longer than 35:32 and seek beond 35:32 timestamp with moodbar enabled.

### Notes
Works good with moodbar disabled.

**Comment by narunlifescience** [comment] 2016-04-19 21:12
duplicate of  #4581

**Closed** 2016-04-20 07:12 UTC
