### ISSUE TITLE
Port to QT5

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3463] opened 2013-12-13 04:27 UTC
_From [ottomodi...@gmail.com](https://code.google.com/u/106575631163387527436/) on January 31, 2013 17:27:00_

People (or at least KDE) are moving to QT5, so Clementine should too! :)
Maybe it's a little too early for this though.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3463_

**Comment by shaforostoff** [comment] 2015-01-26 02:19
https://wiki.ubuntu.com/VividVervet/Alpha2/Kubuntu has KDE5 as default. And fedora is going to have it as well in May release.

with Qt5 your ui is going to be faster on linux because Qt5 uses xcb protocol to communicate with X11, and besides Qt5 supports Wayland, a modern OpenGL-based replacement of X11 (Fedora will ship an experimental Wayland session).

btw I think you can have this task as a GSoC 2015 project

**Comment by Chocobozzz** [comment] 2015-04-07 20:00
Work (slowly) in progress.

**Comment by collectorofbones** [comment] 2016-05-30 09:53
> don't fix when ain't broken
for now it's clear that it IS broken, Gentoo stabilized qt5 and kde plasma. sad story is that even amarok isn't qt5 ready and there seems to be no qt5-music-player available at all ...

how much work it needs to be moved to qt5?

**Comment by Korvox** [comment] 2016-05-30 16:42
Most of it is already done (by Choco) in the qt5 branch, go clone it and break it and fix whatever breaks until it works, or if you cannot fix the bugs make bug reports here tagged with qt5.

**Comment by siddharthist** [comment] 2017-01-13 22:27
Is there a status update on this? Seems like the qt5 branch is still getting updated a lot but it's also been ~8 months since the last post here.

**Comment by Chocobozzz** [comment] 2017-01-14 10:36
See https://github.com/clementine-player/Clementine/issues/5334

**Comment by Fat-Zer** [comment] 2017-03-07 05:24
I may help up on merging qt5 branch workarounds into master (so it would be possible to choose the version against which to build on configuration stage), if it would be appreciated on current stage...

**Comment by supagu** [comment] 2017-07-25 12:03
Is there any eta on when an actual qt5 release will be available for linux? I noticed the solus project distro are also waiting for a qt5 version before adding it to their repo's...

https://dev.solus-project.com/T272

**Comment by horazont** [comment] 2017-08-16 07:37
I would like to mention that [Debian announced yesterday now that they are planning to remove Qt4 in the next release](https://lists.debian.org/debian-devel-announce/2017/08/msg00006.html).

**Comment by Chemrat** [comment] 2017-10-04 17:58
Any reasons why Qt5 branch haven't been merged into master yet? Maybe some bugs that need to be fixed first? Quick glance at issue list doesn't really show anything major, although qt5 label would help.

**Comment by hatstand** [comment] 2017-10-04 18:28
An automated qt5 build for mac & windows as part of our docker images is probably the biggest blocker.

**Comment by pavelvat** [comment] 2017-10-04 19:22
@Chemrat see #5334. For Windows - #5584, #5669 still not merged.

**Comment by peterhoeg** [comment] 2017-10-05 00:16
A number of us are having issues with running the qt5 branch ref https://github.com/clementine-player/Clementine/issues/5753.

**Comment by trougnouf** [comment] 2017-11-06 13:18
@peterhoeg isn't issue #5753 irrelevant to the Qt version?

**Comment by peterhoeg** [comment] 2017-11-07 02:28
It kind of depends - that issue is present on qt4 and 5, yes, but in terms of getting the qt5 version ready it's still a critical issue.

**Comment by a17r** [comment] 2017-11-19 10:34
@peterhoeg if it's not a regression relative to master but to the last release, that would not block merge to master though. It would need to be fixed in master as well, anyway.

**Comment by plater** [comment] 2018-01-04 07:31
openSUSE is in the process of removing libQtWebKit4, haven't looked at how this affects the functionality yet.

**Comment by a17r** [comment] 2018-01-04 13:27
>openSUSE is in the process of removing libQtWebKit4, haven't looked at how this affects the functionality yet.

@plater None I can see, the dep is long gone with just some leftover in the CMakeLists.txt.

**Comment by plater** [comment] 2018-01-04 14:15
Good to know, any idea when the qt5 branch will be merged?
I'm slowly packaging it and will test it myself.
I maintain clementine for openSUSE.

**Comment by K73SK** [comment] 2018-01-20 16:44
Agreed, if this can be done asap that'd be great. Just removed all the QT4 stuff from my Gentoo install to find out that Clementine didn't have a QT5 update... Not going to go through the hell/mayhem I went through to get QT4 completely removed just for Clementine. Unfortunately, this also means I need a temporary alternative to Clementine in the meantime. Clementine is my fav. audio player - the sooner the better!

**Comment by Chemrat** [comment] 2018-01-20 17:51
`media-sound/clementine-9999` in Gentoo uses Qt5 branch

**Comment by ChauhanT** [comment] 2018-01-20 17:53
In this day and age. Why gentoo ? T__T

**Comment by a17r** [comment] 2018-01-20 17:53
That's a strange question, but let's stay ontopic here.

**Comment by K73SK** [comment] 2018-01-21 00:03
@Chemrat That worked perfectly, thank you! Glad to be back on Clementine already :)

**Comment by luigino** [comment] 2018-03-08 11:49
Is there an ETA for this?

**Comment by fitojb** [comment] 2018-04-15 07:08
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874850, tracking Qt4 removal from Debian Buster.

**Comment by gracicot** [comment] 2018-06-13 23:06
There is already discussions about qt6: http://blog.qt.io/blog/2018/06/13/qt-contributors-summit-2018-wrap/

**Comment by Sunderland93** [comment] 2018-06-14 18:54
It's a shame that even Qt5 is low priority

**Comment by horazont** [comment] 2018-06-14 19:14
I subscribed to this issue to be kept up to date with progress. I (and I bet a whole bunch of other people, *including* probably the developers) would appreciate it if we could have less "I want this too" or "You are *so* late supporting Qt5" noise in here. If you’re not ready to continue the work to port to Qt5, please don’t take even more time off other peoples hands by spamming their emails.

**Comment by gracicot** [comment] 2018-06-14 22:48
I agree with you @horazont . I didn't meant my update to be one of those message, I thought that Qt6 might coming faster that some of us thought, and that could be valuable information could affect decisions. I'm not deep into Qt, but it's a possibility that they remove some old deprecated stuff when bumping a major version.

**Comment by MartinDelille** [comment] 2018-11-02 09:50
I'm a Qt5 developer specialised in audio and multimedia application. I'll be happy to help. I tried to compile the `qt5` branch but it fails.

Here is my `CMakeOutput.log`: https://pastebin.com/ST49ZfGP

**Comment by sicherha** [comment] 2018-11-02 10:01
FYI, Fedora now ships a Qt5 build of Clementine as of F29.
https://src.fedoraproject.org/cgit/rpms/clementine.git/tree/

**Comment by MartinDelille** [comment] 2018-11-02 10:08
I'm on macOS 10.13 for your information.

**Comment by a17r** [comment] 2018-11-08 22:04
@MartinDelille: This is not the right place for your specific issue, you should probably open a separate issue and attach a verbose `build.log`.

**Comment by JulianVolodia** [comment] 2019-11-07 13:49
@hatstand probably also could be closed! :)

**Closed** 2019-11-07 14:10 UTC
Labels: Priority-Low, enhancement, imported
