### ISSUE TITLE
Clementine doesn't write album cover to tag

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#5195] opened 2016-01-11 13:49 UTC
If I update song's cover (load from disk) - the cover is updated only in clementine. In any other players (banshee, vlc, itunes) - there is old / no cover

EDIT: clearing clementine config files - removed my cover. So it is stored in local database, not in track

**Comment by davidsansome** [comment] 2016-01-12 00:31
Duplicate of #1176

**Closed by davidsansome** 2016-01-12 00:31 UTC

**Comment by JoseBarakat** [comment] 2016-12-01 08:27
Embedding Artwork should be explained in Wiki tab, FAQ section (because is a VERY Frequently Asked Question).

**Comment by 89z** [comment] 2021-02-26 21:02
https://github.com/clementine-player/Clementine/issues/1176
https://github.com/clementine-player/Clementine/issues/4043
https://github.com/clementine-player/Clementine/issues/4106

https://github.com/clementine-player/Clementine/issues/5195
https://github.com/strawberrymusicplayer/strawberry/issues/286
