### ISSUE TITLE
Deezer

### ISSUE THREAD

**Issue by lobodetaipas** [clementine-player/Clementine#5245] opened 2016-02-09 21:10 UTC
Ok its been 3 years of the last request for it.
I think now it finally can happen

**Comment by Chocobozzz** [comment] 2016-02-10 12:53
Do they have a streaming API?

**Comment by lobodetaipas** [comment] 2016-02-10 13:08
I dont know technical details, but they havê in they develeopers section
Em 10/02/2016 10:53, Bigard Florian <notifications@github.com> escreveu:Do they have a streaming API?

**Comment by Chocobozzz** [comment] 2016-02-10 13:39
Duplicate of https://github.com/clementine-player/Clementine/issues/3531

It seems they still don't have a streaming api for desktop application.

**Closed by Chocobozzz** 2016-02-10 13:39 UTC

**Comment by lbssousa** [comment] 2016-06-21 12:15
Deezer has released a "Native SDK" in April 2016:

http://developers.deezer.com/sdk/native

Maybe it has what you want for integrating the service with Clementine.
