### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by Eluminae** [clementine-player/Clementine#6465] opened 2019-11-26 08:43 UTC
Hello there !

I'm on VoidLinux and we only have access to the 1.3.1 cause there is no release after this one.
The fact is I got an instant "Segmentation Fault" and I'm not sure if this is a fixed bug.

What is the plan about releases ?

**Comment by matkoniecz** [comment] 2019-11-27 11:08
Duplicate of #5958 from 2018

**Comment by JulianVolodia** [comment] 2019-11-28 20:38
Hi @Eluminae three things from me:

1) Have you tried clementine build from source which will be 1.3.1-patchNumber instead of lastest release? This will find the answer if this is still a bug for Void Linux. I consider you should know how to compile if you use Void Linux which seems to me (after 2min of googling) quite advanced distro.

2) As @matkoniecz said - this is issue (about release) is duplicate.
If I could please you to:
- (a) close this one 
- split it into 2 threads:  (b) one on #5958 (i.e. with subscribing that issue) and (c) second, *only if problem persists on current Clementine master branch* build and run on with your distro.

3) If problem persists please use debug version of clementine and file issue.

That's all I could say today.

**Comment by matkoniecz** [comment] 2019-11-28 20:58
>  If I could please you to: (a) close this one

As I am neither author of the issue, nor Clementine contributor I am unable to close it.

**Comment by JulianVolodia** [comment] 2019-11-28 23:54
Dear @matkoniecz read again my comment. I was just refering that I agree with you and this three points are to @Eluminae .

Best.

**Comment by ZeZiNhOo** [comment] 2019-11-29 07:15
Maybe the README file could be changed to reflect the team does no releases?
I wonder why, but still as it is a fact, let's say it. No talking about the website that looks dead!

**Comment by Eluminae** [comment] 2019-11-29 08:49
>  I consider you should know how to compile if you use Void Linux which seems to me (after 2min of googling) quite advanced distro.

Yes but we need a fixed tagged release to build for VoidLinux. We do not package anymore commit references or rc tags.

**Closed** 2019-11-29 08:54 UTC

**Comment by JulianVolodia** [comment] 2019-11-29 17:55
> changed to reflect the team does no releases?

@ZeZiNhOo which part of my comment haven't you read? Are you joking? Who told you that? If you think that was in my comment show me exactly *where*. Really. Comments like this don't help. Read more about some theory of development or talk on some meet-up but we haven't turn into bananas a.k.a. perpetual beta. Really, that it not need to sorry, but think what you write. I read a bunch of comments and issues to get a rid of this 2k issues some time, and really please think twice before saying and attacking. What is bad if you have *literally* claimed to check BETA before filing the issue? You think that what is purpose of 2k issues open out there? Comments like yours.
Have you notifications turned on for all repos of Clementine to say this stuff?

@Eluminae I understand. Do your compiler have a so close integration to Git that you cannot check on this distro, because the problem could not be on Clementine but on distro. If you decided to use exotic one, deal with it Man. I think we are adult (or mentally adult if you are not grown up, I don't know).

Or, jump to Ubuntu. Or, smash the tear drops, get up, try the Beta version, say it works/not works/you don't work, and *this would help us*. Not telling your distro have childhood type of problems with releases.

Still, there will be the release, but there is **_no point in doing release until we have a lot of issues and not well tested version on master_**. But it gets better. We moved to Qt5 and all you need to know it is just 0,5 meter or less from you. This issue tracker and git repo history.

@ZeZiNhOo I don't remember when I was fed up with sb's respond last days so much :(((

**Comment by matkoniecz** [comment] 2019-12-14 13:32
> Or, smash the tear drops, get up, try the Beta version, say it works/not works/you don't work, and this would help us.

I would be happy to do that! I am currently doing a test install of a new OS version, and I will test Clementine on a blank Ubuntu 18.04.

What you think about adding this kind of info to the readme? Maybe there are other people unable to help with development but also interested in helping with testing?

**Comment by ZeZiNhOo** [comment] 2019-12-16 11:49
> @ZeZiNhOo which part of my comment haven't you read? [... ]I hope at the end that was some kind of misconception or lack of understanding and knowledge about another issues and project life.

Well,  I think so. As you answered please try latest git commit, and I see most distros use a git commit as release... I concluded that you do not do releases anymore.

I understand now I was wrong ;-)

**Comment by JulianVolodia** [comment] 2019-12-29 05:32
@ZeZiNhOo as I see that you quoted un-spoiled [...] part of my comment even mistyping space in such a small piece of comment, I see you *completely* **not understand** what I have written not because you can't but you won't Babe. CU

**Comment by JulianVolodia** [comment] 2019-12-29 05:40
> What you think about adding this kind of info to the readme? Maybe there are other people unable to help with development but also interested in helping with testing?

There is a bunch of info how to do development. I don't think it is show stopper for ppl. I think they must pay with some time and stick with it. Btw. I still need to do more of this so we are on same boat.

If you indeed see problems with development build instructions of course you should provide feedback.

Btw. register on CircleCI with your account and do builds there not only for some machine like Ubuntu distro. Everything should work flawlessly just after forking repo, registering there, and marking your clementine fork for building on CI service. C:
