### ISSUE TITLE
Qt5 build: Echonest was not declared

### ISSUE THREAD

**Issue by Israphel** [clementine-player/Clementine#5113] opened 2015-11-12 13:14 UTC
Linux Distro: [ChakraOS 2015.11](https://chakraos.org/news/index.php?/archives/156-Chakra-2015.11-Fermi-released.html) (based on ArchLinux, actual packages come from here)

Clementine won't build with these lines on main.cpp

```c++
Echonest::Config::instance()->setAPIKey("DFLFLJBUF4EGTXHIG");
  Echonest::Config::instance()->setNetworkAccessManager(
     new NetworkAccessManager);
```

If I comment them, it compiles. But I don't know what they actually do.

Also, every
```c++
#include <Artist.h> 
```
must be replaced with:
```c++
#include <echonest5/Artist.h>
```

As commented by **pavbaranov** on [AUR](https://aur.archlinux.org/packages/clementine-qt5-git/?comments=all)

**Comment by Chocobozzz** [comment] 2015-11-12 13:17
Please, specify your GNU/Linux distribution.

**Comment by Israphel** [comment] 2015-11-12 13:22
I added more info and references, thanks.

**Comment by Chocobozzz** [comment] 2015-11-12 14:54
I can't reproduce with the AUR package, can you provide me a pastebin with the cmake (without cache)/make output?

**Comment by Israphel** [comment] 2015-11-12 15:11
I used git clone -b qt5 https://github.com/clementine-player/Clementine.git, not the AUR.

Output: http://pastebin.com/pSXwjYBQ

**Comment by Chocobozzz** [comment] 2015-11-12 15:42
I don't understand why it doesn't work, the *echonest* directory is found here https://github.com/clementine-player/Clementine/blob/qt5/CMakeLists.txt#L374 and we cannot specify

    #include <echonest5/Artist.h>

since some distributions (fedora for example) use *echonest* as include directory (instead of *echonest5*).

**Comment by Israphel** [comment] 2015-11-12 17:17
I don't know... but tweaking the AUR pkgbuild I could compile without touching anything related to Echonest.

But: libmygpo-qt4 must be present, or it fails.

**Comment by Chocobozzz** [comment] 2015-12-19 09:53
Closing this issue, feel free to reopen/comment if you experienced the same issue.

**Closed by Chocobozzz** 2015-12-19 09:53 UTC
