### ISSUE TITLE
Duplicate Entries in Library

### ISSUE THREAD

**Issue by jlanzarotta** [clementine-player/Clementine#4428] opened 2014-07-01 12:31 UTC
Steps used to reproduce this issue:
1. I am using Clementine on a Laptop.
2. All song and podcasts are located on my NAS.
2. Have Clementine build the Library from the songs on that drive.  Access is \\NAS\Media\Music and \\NAS\Media\Podcasts
3. Disconnect Laptop from network where NAS is attached to.
4. Restart Clementine.
5. Clementine will rescan Library.
6. All files are now duplicated.

**Comment by Chocobozzz** [comment] 2015-06-11 08:28
Duplicate of https://github.com/clementine-player/Clementine/issues/1785

**Closed by Chocobozzz** 2015-06-11 08:28 UTC
