### ISSUE TITLE
Equalizer issue

### ISSUE THREAD

**Issue by labaxp** [clementine-player/Clementine#4832] opened 2015-04-28 22:31 UTC
Hi,
There is an issue in the equalizer on my Ubuntu 14.04.
The 16k bar is reverse. So lowering the bar will increase the 16khz frequency and vice versa.
I hope this is not only on me.

**Comment by ArnaudBienner** [comment] 2015-04-29 08:23
Duplicate of #695

**Closed by ArnaudBienner** 2015-04-29 08:23 UTC
