### ISSUE TITLE
cmd-Q keyboard shortcut doesn't quit Clementine on non-english keyboard layouts

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3662] opened 2013-12-13 04:38 UTC
_From [mix...@gmail.com](https://code.google.com/u/102096592967236872441/) on May 07, 2013 19:25:25_

What steps will reproduce the problem? 1. Launch Clementine
2. Type cmd-Q What is the expected output? What do you see instead? Clementine should quit. Instead, the Search in the playlist field becomes active with the cursor blinking in it. What version of the product are you using? On what operating system? Clementine 1.1 with Mac OS X 10.6.8

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3662_

**Comment by ArnaudBienner** [comment] 2015-03-14 00:12
Duplicate of #4708, which has been fixed recently.

**Closed by ArnaudBienner** 2015-03-14 00:12 UTC
Labels: bug, imported, Priority-Medium
