### ISSUE TITLE
Shuffle order is always the same

### ISSUE THREAD

**Issue by Infernal01** [clementine-player/Clementine#5664] opened 2017-03-15 08:10 UTC
- Operating System: Mac OS
- Clementine version: latest (1.3.1)

I expect each time i hit next while in shuffle mode, i would get a random song. However the order list is identical each time you start clementine.

Steps to reproduce the problem:
1. Start Clementine, select Playlist -> Shuffle mode -> Shuffle all
2. Play a few songs, write them down
3. Close Clementine
4. Open Clementine
5. Play a few songs, they will be the same as last time

Note: It seems that pressing the Stop button will create a new shuffle order but if you restart clementine you will still get the first song order.

Relevant maybe: This problems has been reported in 2010 and marked as fixed in ticket https://github.com/clementine-player/clementine/issues/571

**Comment by santigl** [comment] 2017-03-24 03:26
After you restart (I assume you close Clementine while it's playing to not hit *stop*), do start by playing the same first track you chose to start before?

(I am doing that in Linux and I am getting different tracks after the first one.)

**Comment by Infernal01** [comment] 2017-03-24 06:15
Closing and starting Clementine will have the last song i listened to and when i hit next, it will resume with the pre-defined order.

**Comment by santigl** [comment] 2017-04-03 15:40
You mean you hit *next* or *previous* after you restart?

For example, if it played [1, 5, 7] and then you restarted Clementine, 7 would be selected, right? What track would it play when you press next?

**Comment by Infernal01** [comment] 2017-04-04 05:45
If it played [1, 5, 7] and then i restart Clementine, 7 is selected. When i press next, 1 will start playing.

**Comment by santigl** [comment] 2017-04-04 14:41
No, I couldn't recreate with the current master version on Linux: it continues playing the latest track, but it skips to different ones when I hit *next*.

I would say you try with the lastest version from the repo, but the Mac builds are broken. Can you compile it from source?

**Comment by Infernal01** [comment] 2017-04-05 06:12
I can try if you give me a general idea on how to do that :)

Windows version also works fine, it's only Mac that has this problem apparently.

**Comment by gordon-morehouse** [comment] 2017-05-23 23:13
Dupe of #5201?

**Closed** 2017-05-24 08:09 UTC
