### ISSUE TITLE
Some tracks get black moodbar

### ISSUE THREAD

**Issue by liftarn** [clementine-player/Clementine#5217] opened 2016-01-19 13:14 UTC
Some tracks just shows solid black in the moodbar and I think they shouldn't.

Example file https://www.dropbox.com/s/ehejvly5qgcirs4/02%20Last%20Ninja%202%20-%20Central%20park%20metal%20remix.mp3?dl=0 

Still there in version 1.2.3-1501-gc4c094a

**Comment by narunlifescience** [comment] 2016-01-19 13:19
I get the following moodbar for the attached file:
![moodbar](https://cloud.githubusercontent.com/assets/11949260/12419628/f7956d6a-be7c-11e5-9d16-e6d8b6e3fee0.png)

**Comment by liftarn** [comment] 2016-01-19 14:21
Strange. I tried again with the same result.
![moodbar](https://cloud.githubusercontent.com/assets/4818861/12421013/496eb82e-bec0-11e5-9d74-8c4e44bceef3.png)

**Comment by narunlifescience** [comment] 2016-01-19 14:33
Hmm.. lets see if some one else could reproduce this..

**Comment by liftarn** [comment] 2016-01-19 15:03
I get the same with 1.2.3-1510-g8eec786 is that is of any help. Running under Windows 7.

**Comment by Ferroin** [comment] 2016-01-19 15:09
I've seen this before a couple of times, but every time I saw it I just deleted the .mood file from my library, restarted Clementine, and it worked fine.  I've seen this both on Windows 7 (with whatever the most recent stable version was for Windows) and on Gentoo Linux (which I rebuild from the git repo on a roughly weekly basis), but it was at least a month or two ago when I last saw it.  It might be worth noting that I've only seen this with MP3 files, not with FLAC, Vorbis, or WAV (although in the case of Vorbis and WAV files I just may not have enough to actually reasonably expect to see it).

**Comment by TheUbuntuGuy** [comment] 2016-01-19 16:17
That file generates fine for me as well. The last time I saw any moodbar errors was when the code was last rewritten and there were no concurrency locks on the external FFT library calls. Since that was fixed I've generated >100,000 moodbars without any issue on both Linux and Windows. @liftarn How often does this happen? Can you enable the 'Moodbar' column in the playlist view and find out the rough percentage of tracks are not generating.

**Comment by narunlifescience** [comment] 2016-01-19 23:13
I don't find anything wrong with the mp3 file. Here is the spectrum analysis of the file :
![spectrum](https://cloud.githubusercontent.com/assets/11949260/12434594/51d728ae-becd-11e5-8ea5-1a2123c5c39f.png)
which more or less match the moodbar generated by clementine(atleast for me)
![moodbar](https://cloud.githubusercontent.com/assets/11949260/12434651/af28c9c2-becd-11e5-8b61-d0c5a6490bc7.png)
A possibility I could think of is when you generate the mood file using an old version of clementine(which had many problems with moodbar generation like the one you mentioned) and when you subsequently updated clementine the old mood files(generated using old versions of clementine) remained there untouched. when ever you play the song the old mood files gets loaded. @liftarn  could you try to delete the problematic mood files and regenerate them ? I think that should fix the issue. @Ferroin 's reference to a similar issue also fits this argument.

**Comment by liftarn** [comment] 2016-01-20 08:09
It is very rare (less than one in 200, probably way less) but it is very consistent in what files it is for.
I don't save .mood files in my music library. Are they then generated on the fly or are they stored somewhere (if so where?).

**Comment by liftarn** [comment] 2016-01-20 09:09
Ok, I found and deleted the moodbarcache and it seems like that solved the problem.
I think this can be closed now.

**Comment by narunlifescience** [comment] 2016-01-20 10:13
Great! If you find no more broken moodbars, probably you can close this for now.

**Closed** 2016-01-20 11:14 UTC
