### ISSUE TITLE
Clementine ignores all but first instance of tag in a music file

### ISSUE THREAD

**Issue by SheamusPatt** [clementine-player/Clementine#4894] opened 2015-06-09 06:31 UTC
Most of my music files repeat at least some tags multiple times, because the underlying recording has multiple values for the tag. E.g. recordings usually have multiple performers so a file might have these PERFORMER tags:

jim@fuzzy:$ metaflac --show-tag=performer 01\ Sweet\ Jane.flac 
PERFORMER=Alan Anton (bass)
PERFORMER=Peter Timmins (drums)
PERFORMER=Jeff Bird (harmonica, mandolin and percussion)
PERFORMER=Michael Timmins (guitar)
PERFORMER=Ken Myhr (guitar)
PERFORMER=Margo Timmins (vocal)

In Clementine, though, I only see the first tag. In this case, I only see Performer: Alan Anton (bass). I'd really like to see them all. 

In case this is encoding-specific, my music files are mostly encoded as FLAC files.

**Comment by Chocobozzz** [comment] 2015-06-17 13:31
Duplicate of https://github.com/clementine-player/Clementine/issues/4894

**Closed by Chocobozzz** 2015-06-17 13:31 UTC
