### ISSUE TITLE
spotify fail to connect

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3930] opened 2013-12-14 03:57 UTC
_From [patrick....@gmail.com](https://code.google.com/u/108546947328634219609/) on October 29, 2013 18:41:14_

What steps will reproduce the problem? 1.click configure spotify
2.enter username and password
3.click Login
4.popup Bad username and/or password What is the expected output? What do you see instead? I use the same identifiers to log onto the website, so obviously that is not it ;) What version of the product are you using? On what operating system? clementine 1.2 Mac Lion Please provide any additional information below. It's a US spotify account so I guess the api might have a different address

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3930_

**Comment by Kwaadpepper** [comment] 2015-07-23 18:05
this is duplicate of https://github.com/clementine-player/Clementine/issues/4873
I just updated clementine from the repove version 1.2.3 to Version 1.2.3-1259-ga568250
and i have this problem now, whereas it was working previously.

Kubuntu 15.04 kernel 4.0.0-4-generic
Version 1.2.3-1259-ga568250

**Comment by Chocobozzz** [comment] 2015-07-23 18:16
@Kwaadpepper If you have time, can you try to precise the commit after when the bug happen ?

**Comment by Kwaadpepper** [comment] 2015-07-23 18:23
I have first some precisions
```
20:16:27.019 INFO  SpotifyService:355               Starting "/home/kwaadpepper/.config/Clementine/spotifyblob/version15-64bit/blob" 
/home/kwaadpepper/.config/Clementine/spotifyblob/version15-64bit/blob: error while loading shared libraries: libprotobuf.so.7: cannot open shared object file: No such file or directory```

The version i had installed was http://packages.ubuntu.com/vivid/amd64/clementine/download
clementine_1.2.3+dfsg-2build1_amd64.deb

I'm actually trying to make link between the version and a commit but i don't have a clue where to find the info.

**Comment by Chocobozzz** [comment] 2015-07-23 18:26
Try to install protobuf first

**Comment by Kwaadpepper** [comment] 2015-07-23 18:32
i did ```apt-get install libprotobuff* --reinstall``` just to make sure, still no change.
So i have installed ```libprotobuf8          libprotobuf-c1-dbg    libprotobuf-java      libprotoc9            
libprotobuf9          libprotobuf-c-dev     libprotobuf-lite8     libprotoc-dev         
libprotobuf-c1        libprotobuf-dev       libprotobuf-lite9     libprotocol-osc-perl ```

**Comment by Kwaadpepper** [comment] 2015-07-23 18:56
I finally solved the problem by installing ```https://packages.debian.org/wheezy/libprotobuf7```
and after i did this command ```ln -s /usr/lib/libprotobuf.so.7 ~/.config/Clementine/spotifyblob/version15-64bit```

**Closed** 2015-07-23 19:02 UTC
Labels: bug, imported, Priority-Medium

**Comment by joao-gsneto** [comment] 2016-10-19 13:46
UPDATE:

If you have this problem on Ubuntu 16.04 (Xenial) please update to the official clementine build (That uses the correct libprotobuf)

```
sudo add-apt-repository ppa:me-davidsansome/clementine
sudo apt-get update
sudo apt-get install clementine

```

**Comment by thoni56** [comment] 2017-01-03 23:07
Installing from the PPA solved my issues with Spotify login on 1.2.3 which was provided.

**Comment by adwiteeymauriya** [comment] 2017-10-09 15:13
Worked like a charm

**Comment by MartinEtcheverry** [comment] 2019-01-30 13:03
in centos 7 with clementine 1.3.1 still not searching

**Comment by markusk1505** [comment] 2020-03-22 10:55
Hello,
facing issue "invalid signature: blob" again and again under all reachable linuxes (Knoppix, Ubuntu ppa:me-davidsansome..., Debian ). Could somebody please list the complete handling with that binary file/blob for manually completion:
- download (I got with browser taking the argument of the curl-line as address)
- signature?
-?
Thanks
Markus

**Comment by markusk1505** [comment] 2020-04-06 13:43
Now _weeks later_ I have the answer for my issue:
Don't forget to adjust blob-installation to your architecture. After modifying all names with 64bit to 32bit, it installs. It is described [here](https://askubuntu.com/questions/363555/how-do-you-install-spotify-for-clementine-1-2/363901)
Now I have the problem that it is not connecting to spotify, expressed by logs after starting from commandline. I cannot install the ppa, as I'm not on ubuntu. I need a solution for debian alike kwaadpepper did.
So, does anyone know which libproto-version to install for clementine-version 1.3.1?

**Comment by Kwaadpepper** [comment] 2020-04-10 17:16
I think the new solution is https://github.com/librespot-org/librespot

**Comment by markusk1505** [comment] 2020-04-11 13:44
Me too, I hope so. Until now it is not possible for me to compile or build. Yes, build was OK, but I got runtime error  WireError (InvalidEnumValue(13)) that should be resolved since a year or two and this one with _new_ build. Thats only a point because the reading taking precaution additional to the last (?) issue-thread says to build for new.

Another question is how might look the devicename in the run-command 
/target/release/librespot --username SPOTIFY-NAME --cache DIR --name DEVICENAME
-> USB Audio (aplay -l) for external snd-card or plughw:0,0 (aplay -L)? The latter is where I get test-sound. But that does not avoid WireError.

Please, where can I post my strace i.e. describe the error?

Markus

Am 10. April 2020 19:16:39 MESZ schrieb "Jérémy Munsch" <notifications@github.com>:
>I think the new solution is https://github.com/librespot-org/librespot
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/clementine-player/Clementine/issues/3930#issuecomment-612128426

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Kwaadpepper** [comment] 2020-04-11 13:56
Looking here https://github.com/librespot-org/librespot/wiki/Options and this command after build
```target/release/librespot -n "Librespot" -b 320 -c ./cache --enable-volume-normalisation --initial-volume 75 --device-type avr```

So ```-name``` is the long option for ```-n``` DEVICENAME is an arbitrary name like "My private room" or "John's laptop"
