### ISSUE TITLE
Seafile Service returns 404 errors, then Clementine segfaults

### ISSUE THREAD

**Issue by aarqon** [clementine-player/Clementine#4824] opened 2015-04-23 00:08 UTC
I have been trying to set up Clementine as a remote music player on an Ubuntu 14.04 server.
I have a large folder of music uploaded in Seafile on the same server, which so far works without issues.

When I try to connect to Seafile from Clementine, it connects and retrieves my credentials without an issue, and lets me select a library to sync from.
Once the syncing starts, the progress bar shoots to 90%, and the console output begins to fill up with 404 responses from the server. Eventually, Seafile decides that it is seeing too many requests, and begins rejecting attempts outright.

Clementine continues to make connection attempts, at a stunning speed, until it eventually segfaults and kicks me back to the console.

Log: http://pastebin.com/0ThFZ3XB
Sometimes it segfaults, sometimes it just spits me back out to the prompt, like that.

**Comment by Chocobozzz** [comment] 2015-04-23 07:09
How many musics do you have on the Seafile server ? And what is your seafile server version ?

**Comment by Chocobozzz** [comment] 2015-04-23 10:04
I reproduced. I suspect an issue with the Seafile api, because I can reproduce de 404 with curl. And if I change the name of the file which returns 404, wait for sync, and then reput its old name it works.

I'll try to investigate.

**Comment by aarqon** [comment] 2015-04-23 17:24
We have around 5000 songs.
We are running 4.1.2.

**Comment by Chocobozzz** [comment] 2015-05-27 14:46
See https://github.com/haiwen/seafile/issues/1195

**Comment by Chocobozzz** [comment] 2015-07-09 10:09
The original issue was fixed but there is another one https://github.com/haiwen/seahub/issues/677

**Comment by Chocobozzz** [comment] 2015-10-16 12:33
Fixed with Seafile server >= 4.2.1

**Closed by Chocobozzz** 2015-10-16 12:33 UTC
