### ISSUE TITLE
soundcloud login error

### ISSUE THREAD

**Issue by ghost** [clementine-player/Clementine#5766] opened 2017-06-19 22:55 UTC
https://soundcloud.com/connect?response_type=code&client_id=2add0f709fcfae1fd7a198ec7573d2d4&state=33384&redirect_uri=https://clementine-data.appspot.com/skydrive&scope=non-expiring

clementine invalid_client: The client identifier provided is invalid.

**Comment by bastimeyer** [comment] 2017-06-22 08:09
I'm having the same issue. This looks like the Soundcloud client-id of Clementine has either expired or has been revoked by Soundcloud. Can someone confirm this please?

Does Clementine even respect the ToS of Soundcloud?
https://developers.soundcloud.com/docs/api/terms-of-use
https://developers.soundcloud.com/docs/api/terms-of-use#general

> You must not remove or attempt to remove or interfere with any advertising delivered via the SoundCloud® API.
> You must not alter or remove any trademark, copyright or other proprietary or legal notices contained in, or appearing on, the SoundCloud® platform, any User Content and/or any documentation relating to the SoundCloud® API.

Also, API calls are limited by 15000 per day per registered app. This doesn't seem much for an application like Clementine. Does/did the current client-id have a special limit?

You could try to [request a new custom client-id](http://soundcloud.com/you/apps/new) in the mean time and change it here
https://github.com/clementine-player/Clementine/blob/7bd0639455de082f83dcf2344c824e66a4daec32/src/internet/soundcloud/soundcloudservice.cpp#L49-L52
and then recompile. All app registrations are validated by Soundcloud first though and using multiple registrations for the same application is against the ToS, so I'm not sure if this will be successful.

**Comment by MoHD20** [comment] 2017-06-23 07:32
I'm having this same issue right now too

**Comment by zecho** [comment] 2017-06-23 07:54
I'm having the same issue.

**Comment by sonic2kk** [comment] 2017-06-25 21:49
Having this issue too.

**Comment by ArnaudBienner** [comment] 2017-07-19 14:43
I requested the SoundCloud API key for Clementine a while ago.
I have to confess I don't use SoundCloud much nowadays.
Seems like the key was indeed revoked.
Not sure why. I will try to request a new one.

**Comment by ArnaudBienner** [comment] 2017-07-19 14:52
"SoundCloud Application Registration
Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient."
:(

**Comment by djbobyd** [comment] 2017-07-21 15:07
This might explain some things .... 
https://www.musicbusinessworldwide.com/ouch-soundcloud-losses-show-a-broken-business-model-in-desperate-need-of-a-fix/

**Comment by gabsoftware** [comment] 2017-09-30 18:10
Will this be fixed one day?

**Comment by malik-albahlani** [comment] 2017-10-14 04:30
This is a duplicate of [this](https://github.com/clementine-player/Clementine/issues/5538).

**Comment by rolfen** [comment] 2018-01-30 20:45
This is an issue with Soundcloud, apparently. I think it would be good to be able to change the API key without recompiling. Maybe in a config file, or a GUI input in settings (although many would not care for it).

**Comment by sonicwim** [comment] 2018-05-10 16:06
It's still broken... :-(

**Comment by jorgeas80** [comment] 2018-08-24 08:50
Still not working :-(

**Closed** 2018-10-01 16:48 UTC

**Comment by gabsoftware** [comment] 2018-10-05 05:48
Well they removed SoundCloud support instead of fixing it, without commenting on this. That was not nice.

**Comment by rolfen** [comment] 2018-10-05 09:14
> Well they removed SoundCloud support instead of fixing it, without commenting on this. That was not nice.

Soundcloud is making it really hard to fix this one.

In one of the duplicate issues someone mentioned rewriting the app to sure "web endpoints" instead of "Soundcloud API". I don't know much more.

Yes an update would be nice, however it does not change much for me.

**Comment by lkorczowski** [comment] 2018-12-25 09:48
Why does this issue has been closed? I don't think it has been fixed.

**Comment by sonicwim** [comment] 2018-12-25 13:56
I don't think they'll bother fixing it...

**Comment by jonaski** [comment] 2018-12-25 15:41
Soundcloud is not open to API registration

**Comment by JulianVolodia** [comment] 2019-11-24 23:00
Dear @sonicwim @lkorczowski @tomachinz @rolfen @gabsoftware @jorgeas80 @bastimeyer @MoHD20 @zecho and @sonic2kk  

As @jonaski and @ArnaudBienner explaied here and was mentioned here https://github.com/clementine-player/Clementine/issues/6294#issuecomment-466768585 the support is dropped.

What could be done to you users to improve your experience?

**Comment by jorgeas80** [comment] 2019-11-26 15:50
@JulianVolodia thanks for the update. I understand your reasons. So, no problem.

**Comment by SJS-dev** [comment] 2021-02-25 14:09
you can get RSS feed.  is there an easy way to determine the RSS feed for soundcloud podcast?  
https://feeds.soundcloud.com/.../soundcloud.../sounds.rss

**Comment by JulianVolodia** [comment] 2021-03-04 21:04
@SJS-dev what exactly You are asking about? Help with re api of sc? or whut?

**Comment by examachine** [comment] 2021-05-26 09:26
still can't login
