### ISSUE TITLE
Can't update albumartist tag on ogg files

### ISSUE THREAD

**Issue by acurl** [clementine-player/Clementine#5001] opened 2015-08-16 18:07 UTC
Hi!

Clementine does not update albumartist tag on ogg files when I change it. It's written in bold in the tag editor, but when saving, the window is closed and nothing changes.
I tested with m4a files and there is no problem.
All my ogg files are created by converting flac files with oggenc.

Clementine 1.2.3
Ubuntu 12.04

**Comment by Chocobozzz** [comment] 2015-08-16 18:09
Duplicate of https://github.com/clementine-player/Clementine/issues/1624

**Closed by Chocobozzz** 2015-08-16 18:09 UTC

**Comment by acurl** [comment] 2015-08-16 18:15
It's not the same issue. Clementine sees the albumartist tag and sorts correctly my collection. When I open the tag editor, I see the current value for the albumartist tag. But it's not updated if I modify it.

**Comment by acurl** [comment] 2015-08-16 18:17
oh sorry, I didn't read the last comment
