### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by adl-88** [clementine-player/Clementine#5020] opened 2015-09-03 04:24 UTC
Is there a way to hide/disable the sidebar I've framed in red? I would appreciate it.

![test](https://cloud.githubusercontent.com/assets/14103250/9650522/66b5d8aa-5204-11e5-99b5-957195d36d46.png)

**Comment by Chocobozzz** [comment] 2015-09-03 11:24
Duplicate of https://github.com/clementine-player/Clementine/issues/938

**Closed by Chocobozzz** 2015-09-03 11:24 UTC
