### ISSUE TITLE
no results for soundcloud search

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3983] opened 2013-12-14 08:31 UTC
_From [mr.magic...@gmail.com](https://code.google.com/u/116988937950310617388/) on November 24, 2013 00:32:43_

What steps will reproduce the problem? 1. Try to search something on soundcloud (like "frog")
2. No results in Clementine but many on soundcloud.com 3. What is the expected output? What do you see instead? No results What version of the product are you using? On what operating system? 1.2 (wheezy) on Linux Mint Debian Edition (Up 7)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3983_

**Comment by ArnaudBienner** [comment] 2016-02-03 09:16
Seems like a duplicate of #4794 which was fixed some time ago.

**Closed by ArnaudBienner** 2016-02-03 09:16 UTC
Labels: bug, imported, Priority-Medium
