### ISSUE TITLE
SoundCloud Error

### ISSUE THREAD

**Issue by COOLIRON2311** [clementine-player/Clementine#5914] opened 2017-11-20 16:19 UTC
invalid_client: The client identifier provided is invalid.

This pops up in browser when connecting to SoundCloud.

Clementine 1.4
macOS High Sierra

**Comment by COOLIRON2311** [comment] 2017-12-23 15:06
still no fix

**Comment by devurandom** [comment] 2018-03-16 04:15
Duplicate of issue #5766.

**Closed** 2018-10-01 16:48 UTC
