### ISSUE TITLE
Spotify blob fails to load

### ISSUE THREAD

**Issue by bazsy01** [clementine-player/Clementine#5232] opened 2016-01-30 19:38 UTC
Using Clementine Version 1.3 rc1 on Ubuntu 14.04.3 64bit.
In settings it downloaded the version15-64bit blob, but faild to connect to Spotify.
console output:

`19:58:48.623 INFO  SpotifyService:356               Starting "/home/bazsy/.config/Clementine/spotifyblob/version15-64bit/blob" 
/home/bazsy/.config/Clementine/spotifyblob/version15-64bit/blob: error while loading shared libraries: libprotobuf.so.7: cannot open shared object file: No such file or directory`

libprotobuf.so.8 is installed, so this is the cause.

Possible fix:
I based on [this](http://askubuntu.com/questions/363555/how-do-you-install-spotify-for-clementine-1-2) I manually downloaded the version16-64bit blob and replaced the ver15 with it. After restarting Clementine, Spotify playback worked flawlessly.

**Comment by ArnaudBienner** [comment] 2016-01-31 20:12
Seems to be what @hatstand fixed few days ago: 8ef1d4cae2ddf8396f650046fa2d77d9041f8696
Could be try one of the latest build and let us know if the problem is fixed now? http://builds.clementine-player.org/
If it is, we will backport this to 1.3

**Comment by bazsy01** [comment] 2016-01-31 20:53
Yes, the [latest build](http://builds.clementine-player.org/ubuntu-trusty/clementine_1.2.3-1514-g8ef1d4c~trusty_amd64.deb) downloaded the v16 blob and works fine.
I think it should be included in the 1.3 release.

**Comment by ArnaudBienner** [comment] 2016-01-31 21:22
I think too.
Thanks for testing :)

**Closed by ArnaudBienner** 2016-01-31 21:22 UTC
