### ISSUE TITLE
a bug in the equalizer

### ISSUE THREAD

**Issue by POSCUDA** [clementine-player/Clementine#4828] opened 2015-04-25 16:25 UTC
Column 16 kHz works the other way, that is, lowering the volume goes up, goes down a promotion. Software version 1.2. Unfortunately, I am not programmer, and he is correct I can not.

**Comment by ArnaudBienner** [comment] 2015-04-25 17:10
Duplicate of #695

**Closed by ArnaudBienner** 2015-04-25 17:10 UTC
