### ISSUE TITLE
Can't play Shoutcast Stream

### ISSUE THREAD

**Issue by TyrasNistru** [clementine-player/Clementine#4977] opened 2015-08-04 15:10 UTC
Version: 1.2.3-1241-gfbe310b
OS: Windows 10

I'm trying to open the stream http://radioarquivodorock.com.br:9998/listen.pls on Clemetine, But it got stuck in "Loading Tracks: 0%"

Trying to reopen the stream without closing and reopening Clementine result in the status bar getting stacked entries ("Loading Tracks: 0%, Loading Tracks: 0%, Loading Tracks: 0%...")

**Comment by Nelsyv** [comment] 2016-04-22 01:10
This is happening to me as well, whenever I try to add the following streams:

http://www.bigblueswing.com:8002/listen.pls
http://50.7.173.162:2199/tunein/jazz.pls
http://50.7.173.162:2199/tunein/enieopyy.pls

OS: Windows 7 SP1
Version: 1.3.1 (the main stable release from the website, I downloaded it today)

**Comment by seanbruno** [comment] 2016-05-03 17:05
Choosing this issue as there appear to be two in the tracker for ShoutCast streams.

Command line attempt to access a known working shoutcast stream (with debug enabled) looks like this in the failure case:

10:02:19.966 DEBUG MainWindow:301                   Creating UI 
10:02:20.188 DEBUG MainWindow:846                   Creating equalizer 
10:02:20.190 DEBUG MainWindow:875                   Creating now playing widget 
10:02:20.323 DEBUG MainWindow:937                   Loading settings 
10:02:20.343 INFO  NetworkRemote:80                 Network Remote deactivated 
10:02:20.344 DEBUG MainWindow:1016                  Started 
10:02:20.344 DEBUG SongLoader:370                   Loading remote file  QUrl( "http://www.radio-kol.net/64/listen.pls" )  
10:02:20.377 INFO  DeviceManager:405                Device added: "/dev/cd0" 
10:02:21.007 ERROR SongLoader:517                   Could not determine type of stream. 
10:02:21.007 ERROR SongLoader:518                   gsttypefindelement.c(992): GstFlowReturn gst_type_find_element_chain_do_typefinding(GstTypeFindElement *, gboolean, gboolean) (): /GstPipeline:pipeline0/GstTypeFindElement:typefindelement0 
10:02:21.007 ERROR SongLoader:517                   Could not determine type of stream. 
10:02:21.007 ERROR SongLoader:518                   gsttypefindelement.c(992): GstFlowReturn gst_type_find_element_chain_do_typefinding(GstTypeFindElement *, gboolean, gboolean) (): /GstPipeline:pipeline0/GstTypeFindElement:typefindelement0 
10:02:21.008 DEBUG Playlist:1142                    Updating playlist with new tracks' info 
10:02:21.008 DEBUG PlaylistBackend:294              Saving playlist 7 

However, loading WFMU seems to work just fine with their playlist files:

0:04:53.761 DEBUG MainWindow:937                   Loading settings 
10:04:53.764 INFO  NetworkRemote:80                 Network Remote deactivated 
10:04:53.859 DEBUG MainWindow:1016                  Started 
10:04:53.859 DEBUG SongLoader:370                   Loading remote file  QUrl( "http://www.wfmu.org/wfmu.pls" )  
10:04:53.893 INFO  DeviceManager:405                Device added: "/dev/cd0" 
10:04:54.152 DEBUG SongLoader:436                   Mime type is "text/plain" 
10:04:54.152 DEBUG SongLoader:463                   Received total 532 bytes 
10:04:54.152 DEBUG SongLoader:562                   void SongLoader::MagicReady() 
10:04:54.152 DEBUG SongLoader:583                   Magic says "PLS" 
10:04:55.168 DEBUG SongLoader:538                   void SongLoader::EndOfStreamReached() 2 
10:04:55.170 DEBUG SongLoader:340                   Parsing  QUrl( "http://www.wfmu.org/wfmu.pls" )  with "PLS" 
10:04:55.171 DEBUG PlaylistBackend:294              Saving playlist 7 
10:04:55.173 WARN  logging:57                       cannot add interface type 'GstColorBalance' to type 'GstPlayBin' which does not conform to prerequisite 'GstImplementsInterface' 
10:04:55.173 WARN  logging:57                       cannot add interface type 'GstColorBalance' to type 'GstPlaySink' which does not conform to prerequisite 'GstImplementsInterface' 
10:04:55.175 DEBUG PlaylistBackend:294              Saving playlist 7 
10:04:55.187 DEBUG Playlist:1142                    Updating playlist with new tracks' info 
10:04:55.187 DEBUG PlaylistBackend:294              Saving playlist 7 
10:04:55.754 ERROR logging:54                       gst_pb_utils_add_codec_description_to_tag_list: assertion 'GST_IS_TAG_LIST (taglist)' failed 
10:04:57.370 DEBUG Playlist:1669                    Setting metadata for  QUrl( "http://stream0.wfmu.org/freeform-128k" )  to "" ""Paris Face" by Angie on WFMU on Liz Berg's show" 
10:04:57.717 DEBUG Playlist:1669                    Setting metadata for  QUrl( "http://stream0.wfmu.org/freeform-128k" )  to "" ""Paris Face" by Angie on WFMU on Liz Berg's show"

**Comment by seanbruno** [comment] 2016-05-03 17:07
Fetching the playlist file manually and loading it into clementine also seems to just work.  I assume that the handoff between the QUrl handler and the SongLoader is missing something that I don't quite understand.

```
10:07:16.499 DEBUG MainWindow:1016                  Started 
10:07:16.499 DEBUG SongLoader:173                   Loading local file "/home/sbruno/listen.pls" 
10:07:16.500 DEBUG SongLoader:225                   Parsing using "PLS" 
10:07:16.516 INFO  DeviceManager:405                Device added: "/dev/cd0" 
10:07:16.621 DEBUG PlaylistBackend:294              Saving playlist 7 
10:07:16.624 WARN  logging:57                       cannot add interface type 'GstColorBalance' to type 'GstPlayBin' which does not conform to prerequisite 'GstImplementsInterface' 
10:07:16.624 WARN  logging:57                       cannot add interface type 'GstColorBalance' to type 'GstPlaySink' which does not conform to prerequisite 'GstImplementsInterface' 
10:07:16.627 DEBUG PlaylistBackend:294              Saving playlist 7 
10:07:16.639 DEBUG Playlist:1142                    Updating playlist with new tracks' info 
10:07:16.639 DEBUG PlaylistBackend:294              Saving playlist 7 
10:07:16.924 ERROR logging:54                       gst_pb_utils_add_codec_description_to_tag_list: assertion 'GST_IS_TAG_LIST (taglist)' failed 
10:07:17.823 DEBUG Playlist:1669                    Setting metadata for  QUrl( "http://tess.fast-serv.com:8794/" )  to "The Kinks" "All Day And All Of The Night" 
10:07:17.826 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
10:07:17.832 WARN  unknown                          QPainter::translate: Painter not active 
10:07:17.832 WARN  unknown                          QPainter::save: Painter not active 
10:07:17.832 WARN  unknown                          QPainter::pen: Painter not active 
10:07:17.832 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.832 WARN  unknown                          QPainter::pen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::pen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::pen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::pen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::setPen: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::restore: Unbalanced save/restore 
10:07:17.833 WARN  unknown                          QPainter::translate: Painter not active 
10:07:17.833 WARN  unknown                          QPainter::end: Painter not active, aborted 
10:07:18.166 DEBUG Playlist:1669                    Setting metadata for  QUrl( "http://tess.fast-serv.com:8794/" )  to "The Kinks" "All Day And All Of The Night" 
```

**Comment by seanbruno** [comment] 2016-05-03 17:14
Running the following gstreamer1 plugins:
`# pkg info |grep gstreamer1
gstreamer1-1.8.0               Media applications framework
gstreamer1-plugins-1.8.0       GStreamer written collection of plugins handling several media types
gstreamer1-plugins-bad-1.8.0   GStreamer-plugins that need more quality, testing or documentation
gstreamer1-plugins-cdparanoia-1.8.0 GStreamer CDDA extraction (aka audio ripping) plugin
gstreamer1-plugins-chromaprint-1.8.0_1 GStreamer fingerprint audio plugin
gstreamer1-plugins-flac-1.8.0  GStreamer free lossless audio encoder/decoder plugin
gstreamer1-plugins-good-1.8.0  GStreamer-plugins good-quality plug-ins
gstreamer1-plugins-lame-1.8.0  GStreamer High-quality free mp3 encode plugin
gstreamer1-plugins-mad-1.8.0   GStreamer mp3 decoder plugin
gstreamer1-plugins-neon-1.8.0  GStreamer neon http source plugin
gstreamer1-plugins-ogg-1.8.0   GStreamer Ogg bitstream plugin
gstreamer1-plugins-shout2-1.8.0 GStreamer icecast output plugin
gstreamer1-plugins-soup-1.8.0  GStreamer soup based http input plugin
gstreamer1-plugins-taglib-1.8.0 GStreamer taglib plugin for adding APEv2 and ID3v2 headers
gstreamer1-plugins-ugly-1.8.0  GStreamer-plugins set of good-quality plug-ins that might have distribution problems
gstreamer1-plugins-vorbis-1.8.0 GStreamer vorbis encoder/decoder plugin
`

**Comment by gordon-morehouse** [comment] 2017-05-24 00:04
Duplicate of #4842.

**Closed** 2017-05-24 08:17 UTC
