### ISSUE TITLE
Sometimes Clementine stop playing next track.

### ISSUE THREAD

**Issue by mevsme** [clementine-player/Clementine#5501] opened 2016-10-01 10:50 UTC
I am using Clementine to listen my samples packs, 1000-4000 files in playlist, 0-3 sec long. Sometimes Clementine fails to jump on the next track. It is not playing until I press next button. Sometimes it says `bufferig 43%` and freez on that number. Sometimes without saying `buffering`. I am not sure but I think it happens more frequently when the player is on background.

Ubuntu 64bit 15.04
Clementine 1.3.1
Prev version of Clementine had the same issue, but I don't remember what was the version.

**UPD:** in compare to old version, 1.3.1 have crashed 3-4 times without any messages while playing many short files.

**Comment by raphj** [comment] 2018-04-23 12:11
I have the same issue on Clementine on amd64 (Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz) as provided in Debian testing or Ubuntu Bionic and with the master branch as well as the qt5 branch. I'm not sure the problem is present on Ubuntu Artful.


In my playlist I have opus, ogg and mp4 files. It seems to stop at the end of opus songs, but not systematically. Just very often.

**Comment by jamesbroadhead** [comment] 2018-09-04 12:42
I have this on the latest dev build (1.3.1-496-gb04367937). 

This is easily reproducible with a variety of opus files I have. They reach the end of the track (the final second), but Clementine does not proceed onto the next track. There is no unusual output on the CLI

**Comment by nicodorn** [comment] 2018-11-17 17:37
It's definitely opus related. I can trigger the issue easily with the Queue Manager. Steps to reproduce:

1. Playback an opus file.
2. Queue a track which is a flac or ogg file.
Expected result: playback continues.
Actual result: playback halts after the opus file.

The same happens the other way around:
1. Playback an flac or ogg file.
2. Queue a track that is an opus file.
Expected result: playback continues.
Actual result: playback halts after the opus file.

Workaround: Press the Media Next key when Clementine halts.

**Comment by raphj** [comment] 2018-11-17 17:43
I haven't observed the problem for quite some time. Is it not fixed in the git repository?
I use Version 1.3.1-588-gf420f51a6

Here: https://github.com/clementine-player/Clementine/issues/6062#issuecomment-404135463
The problem was related to different sampling rates (44.1 kHz vs 48 kHz).

**Comment by nicodorn** [comment] 2018-11-18 10:42
That's it! My files have different sample rates indeed.

I upgraded from 1.3.1+git276 to 1.3.1+git565 which fixed it for me.

**Comment by raphj** [comment] 2018-11-18 11:08
It would be nice to have a release of Clementine fixing this issue :-)

@mevsme shoud this bug report be closed?

**Comment by martinpescador** [comment] 2018-11-22 20:06
> It would be nice to have a release of Clementine fixing this issue :-)

If that is not going to happen, it would be nice with a clear, easy-to-follow, detailed set of instructions to work around this issue.

**Comment by raphj** [comment] 2018-11-22 20:11
I see 2 workarounds:

1) Compile from sources... instructions here: https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source
2) Convert 48 kHz tracks to 44.1 kHz or vice versa (I would recommend against this)

But let us wait for the clementine developers to make a new release :-)

**Comment by hatstand** [comment] 2018-11-22 20:13
https://builds.clementine-player.org/

**Comment by martinpescador** [comment] 2018-11-22 20:48
> https://builds.clementine-player.org/

@hatstand Thanks for that - an easy to follow instruction, indeed! :)

However, my music machine is running Cosmic/Lubuntu and there is not build for that, as far as I can tell. So, I guess I have to compile from source..... although not really what I wanted to spend my time on, not having a machine set up for that.. :(

**Comment by raphj** [comment] 2018-11-22 20:51
I can't test but you should be fine with the version for bionic or for the latest Debian.

(thanks for the link to the builds server, I didn't know it existed)

**Comment by martinpescador** [comment] 2018-11-22 20:55
[Yes, that is a hidden link!]

I tried the Bionic build. Dependency issues.

**Comment by nicodorn** [comment] 2018-11-23 07:38
> I tried the Bionic build. Dependency issues.

The bionic build has the issue anyway. I'm on bionic with KDE Neon on top and replied to this bug facing the problem. What I did to solve it was to download the disco build: https://packages.ubuntu.com/disco/clementine

In my case the installation failed because of some dependencies. I also had to download libcdio18, liblastfm5-1, and libmygpo-qt5-1. Only in case you need detailed help:

1. Download the Clementine build (the deb file) from https://packages.ubuntu.com/disco/clementine (at the bottom of the page are download links for different architectures).
2. Go to the download directory and do a "sudo dpkg -i *.deb" in the terminal.
3. In case of unfullilled dependencies (the terminal will inform you), download them as well an do a "sudo dpkg -i *.deb" again.

It's worth while, the build 1.3.1+git609-g623a53681 fixed it for me.

**Comment by martinpescador** [comment] 2018-11-23 21:03
>     1. Download the Clementine build (the deb file) from https://packages.ubuntu.com/disco/clementine (at the bottom of the page are download links for different architectures).
> 
>     2. Go to the download directory and do a "sudo dpkg -i *.deb" in the terminal.
> 
>     3. In case of unfullilled dependencies (the terminal will inform you), download them as well an do a "sudo dpkg -i *.deb" again.
> 
> It's worth while, the build 1.3.1+git609-g623a53681 fixed it for me.

Thanks. Since this was a Cosmic release, I used:

https://packages.ubuntu.com/cosmic/amd64/clementine/download

Specifically: clementine_1.3.1+git565-gd20c2244a+dfsg-1_amd64.deb 

Works! :)

**Comment by martinpescador** [comment] 2019-01-20 19:48
> Thanks. Since this was a Cosmic release, I used:
> 
> https://packages.ubuntu.com/cosmic/amd64/clementine/download
> 
> Specifically: clementine_1.3.1+git565-gd20c2244a+dfsg-1_amd64.deb
> 
> Works! :)

Actually, it didn't. What worked was a fresh install of LMDE and the default version of Clementine that came with that.

If anyone who knows anything reads this: Will Clementine be repackaged to fix this?

**Comment by nicodorn** [comment] 2019-01-22 12:19
The Disco build works for me and I'm on Bionic. So, I assume it should also work for you. To solve the inevitable dependency issues I had to install in addition the Disco builds of libcdio18, liblastfm5-1, and libmygpo-qt5-1. Hope that helps.

**Comment by martinpescador** [comment] 2019-01-22 18:55
I ended up compiling the current git version:

git clone https://github.com/clementine-player/Clementine.git
+
https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source

Using checkinstall to get a .deb for future use etc:

https://help.ubuntu.com/community/CheckInstall

But: **An official 1.3.2 would be pretty cool, though! :)**

**Closed** 2019-11-11 23:23 UTC
