### ISSUE TITLE
FR: http://www.radio-browser.info suppert

### ISSUE THREAD

**Issue by gerroon** [clementine-player/Clementine#5878] opened 2017-10-05 01:01 UTC
Hi

http://www.radio-browser.info/ offers probably one of the best radio stations list around the web. I think that Clementine users can benefit from accessing the list directly within Clementine.

thanks

**Comment by h3298** [comment] 2018-11-27 02:54
Duplicate of bug https://github.com/clementine-player/Clementine/issues/5321

**Comment by fitojb** [comment] 2021-03-16 12:22
@hatstand please close this issue as duplicate

**Closed** 2021-03-16 12:28 UTC
