### ISSUE TITLE
The "internet icon" is not nesting properly in the menu

### ISSUE THREAD

**Issue by Philippe-Arnaud** [clementine-player/Clementine#5055] opened 2015-09-28 08:57 UTC
When the left menu is selected as vertical with tabs on top, the "Internet" icon is getting out of its tab.
![capture d ecran - 28092015 - 10 54 03](https://cloud.githubusercontent.com/assets/767823/10131296/868746ee-65cf-11e5-8ee0-7627c00a323f.png)

**Comment by narunlifescience** [comment] 2015-09-28 09:01
that looks like a icon theme issue.. could you please change the icon theme you are currently using and check whether the issue persists ?

**Comment by Philippe-Arnaud** [comment] 2015-09-29 07:11
Sure thing! Unfortunately, I'm not quite sure of how to do it regarding QT...
I'm currently using Xubuntu 14.10.

**Comment by narunlifescience** [comment] 2015-09-29 07:23
although xubuntu is gtk2.0 based, changing xubuntu icon theme from system settings should affect clementine as well. clementine always look for icons first in system theme and then load a fall back icon theme. it looks like the system icon theme have an incorrect icon size. could you tell me what icon theme you are using in xubuntu ?

**Comment by Philippe-Arnaud** [comment] 2015-09-29 17:19
I'm currently using the Numix Circle icon theme. Changing the icon theme in XFCE's setting had not effect, despite rebooting.

**Comment by narunlifescience** [comment] 2015-09-29 17:47
Hmm.. after you change the icon theme, you should quit clementine and restart clementine (make sure clementine is not running in system tray). also, don't change the icon theme to other icon sets provided by numix as they may inherit a common base theme.
I would suggest you to use some icon themes like Faenza for checking. after changing the icon theme, terminate all instances of clementine using xfce task manager and then restart clementine. please provide a screenshot after doing this procedure. a system restart is not required..

if you dont have faenza theme, you can get it from here :  http://ubuntuhandbook.org/index.php/2014/01/install-faenza-icons-ubuntu-14-04/

**Comment by ArnaudBienner** [comment] 2015-09-30 17:17
IIRC this is an old Qt bug. Not sure why it can't be fixed.
There is probably a duplicate already opened (will try to find it later)

**Comment by Chocobozzz** [comment] 2015-09-30 20:33
If @ArnaudBienner is right, it would be interesting to try with the Qt5 branch.

**Comment by ArnaudBienner** [comment] 2015-10-11 19:03
Duplicate of #2298.
So it seems this should be fixed with Qt5 indeed.

**Closed by ArnaudBienner** 2015-10-11 19:03 UTC

**Comment by narunlifescience** [comment] 2015-10-11 19:58
Icon scaling problems should not affect users if they use an icon theme providing all the icon size used by clementine(22x22, 32x32 & 48x48). In this case, @Philippe-Arnaud is using Numix Circle icon theme, which contains all the icon sizes used by clementine. After going through #2298 and the patch provided by @davidsansome, I am not convinced this is a duplicate of #2298. @ArnaudBienner could you check it again, I may be wrong..

**Comment by narunlifescience** [comment] 2015-10-11 20:25
may be it is a duplicate of #2298. when i checked all the folders(numix circle) for applications-internet icon, i could find it only in 48x48 folder. However, i could not reproduce this issue in manjaro running xfce. Icons seems to scale perfectly fine with clementine when using Numix Circle theme.
