### ISSUE TITLE
Please add a real random play mode

### ISSUE THREAD

**Issue by 0mark** [clementine-player/Clementine#5725] opened 2017-05-05 03:19 UTC
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X ] I checked the issue tracker for similar issues
- [ X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Arch Linux
- 1.31

### Expected behaviour / actual behaviour
I miss a random play mode in Clementine. Shuffle is neither the same as random nor "better" than random "what you actually really want". Shuffle is not random at all: shuffle is a linear, ordered playlist which happens to have a random order.
The difference is quite massive: in random, each time a new track is started, one track out of all tracks is selected, it can be the same track, one that was played just a minute ago or one that was never played before. In shuffle, when the track changes its just the next track from the list: each track that was already played wont be played again until the list is played through.
Or short: random means, each time a new track is selected it can be every track i have, and i have absolutely no idea which one it will be. Its really random. With shuffle, i know which songs wont be played next, and i will gather more and more knowledge while it plays along.

**Comment by gordon-morehouse** [comment] 2017-05-23 23:13
Dupe of #5201?

**Closed** 2017-05-24 08:10 UTC

**Comment by 0mark** [comment] 2017-05-24 09:55
I dont think this is a dupe of #5201. In fact, they have virtually nothing in common. 5201 is about a bug in the shuffling function, while this is about a different play mode "random" which is not the same as shuffle.
